 package ai.tech5.finger.utils;

 public enum SegmentationMode
 {
     SEGMENTATION_MODE_LEFT_SLAP,
     SEGMENTATION_MODE_RIGHT_SLAP,
     SEGMENTATION_MODE_LEFT_AND_RIGHT_THUMBS,
     SEGMENTATION_MODE_RIGHT_THUMB,
     SEGMENTATION_MODE_RIGHT_INDEX,
     SEGMENTATION_MODE_RIGHT_MIDDLE,
     SEGMENTATION_MODE_RIGHT_RING,
     SEGMENTATION_MODE_RIGHT_LITTLE,
     SEGMENTATION_MODE_LEFT_THUMB,
     SEGMENTATION_MODE_LEFT_INDEX,
     SEGMENTATION_MODE_LEFT_MIDDLE,
     SEGMENTATION_MODE_LEFT_RING,
     SEGMENTATION_MODE_LEFT_LITTLE,

     SEGMENTATION_MODE_RIGHT_INDEX_MIDDLE,
     SEGMENTATION_MODE_LEFT_INDEX_MIDDLE,

     SEGMENTATION_MODE_RIGHT_RING_LITTLE,
     SEGMENTATION_MODE_LEFT_RING_LITTLE
 }
